# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-03 07:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appy', '0002_position_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('APP', 'Applied'), ('REJ', 'Rejected'), ('INT', 'Interviewing'), ('NEG', 'Negotiating')], max_length=3)),
                ('duration', models.CharField(max_length=64)),
                ('contact_method', models.CharField(choices=[('EM', 'Email'), ('PH', 'Phone')], max_length=2)),
                ('contact_info', models.CharField(max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
